name: shoofha
description: "Shoofha Application"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.0.3
  go_router: ^17.0.0
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  flutter_localizations:
    sdk: flutter
  video_player: ^2.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # ----------------------------------------------------------
  #                    ASSETS SECTION
  # ----------------------------------------------------------
  assets:
    - assets/logo/
    - assets/brand/
    - assets/images/   # لو بدك تستخدم صور للتطبيق لاحقاً
    - assets/icons/    # لو بدك أيقونات خاصة لاحقاً

  # ----------------------------------------------------------
  #                     FONTS SECTION
  # ----------------------------------------------------------
  # إذا عندك خط مخصص للمشروع احكيلي اسمه وارفعه  
  # ورح أضيفه هون.
  # مثال جاهز لو بدك تستخدم خط Cairo:
  #
  # fonts:
  #   - family: Cairo
  #     fonts:
  #       - asset: assets/fonts/Cairo-Regular.ttf
  #       - asset: assets/fonts/Cairo-Bold.ttf
  #         weight: 700
